### ISSUE TITLE
Fixing eccentricity to 0 in light curve fitting

### ISSUE THREAD

**Issue by zihaowrez** [mikecokina/elisa#9]
Hi, I'm fitting a light curve for a detached binary system using ELISa, and I wish to fix the eccentricity to 0. However, once I do that
<img width="224" alt="eccentricity_fixed" src="https://user-images.githubusercontent.com/67496158/141243946-a1bdb80d-f55d-4f31-ab25-817db11ec058.png">
then the system cannot be defined:
```
InitialParamsError: Invalid syntax or value in constraint, name 'system' is not defined.
```
Is there a way to fix the eccentricity to 0? Thank you.

**Comment by mirofedurco** [comment]
Hi,

from a first glance, this should indeed work. Could you please provide us with the rest of the fitting script or some minimal working example that can reproduce this error? 

Miro

**Comment by zihaowrez** [comment]
I'm just using the demo lc_fitting notebook and only the eccentricity is changed.
[lc_fitting_eccentricity_0 - Jupyter Notebook.pdf](https://github.com/mikecokina/elisa/files/7519131/lc_fitting_eccentricity_0.-.Jupyter.Notebook.pdf)

**Comment by mirofedurco** [comment]
Thank you!

The reason for the failure is that once you marked eccentricity as fixed parameter, you removed it from the set of variable model parameters which can be used to define a constrained variable (as for ELISa v0.5). However, you still kept the constraint for the component synchronicities  to be dependent on a eccentricity which is no longer among the variable parameters:

```
"synchronicity": {
            "value": 1.00,
            "constraint": "(1 + system@eccentricity)**2 / (1 - system@eccentricity**2)**(3.0/2.0)",
            "unit": None
        },
```

To fix this problem, you have to rewrite definitions for component's synchronicities. In this case eccentricity = 0 will reduce the constraint to a simple synchronous rotation of the components, i.e.:

```
"synchronicity": {
            "value": 1.00,
            "fixed": True,
            "unit": None
        },
``` 

We did not included fixed parameters as valid entries in definitions of constrained model parameters, since it ignores a purpose of the constrained parameter, that should update according to a current value of a variable model parameter.  If your parameters in constraint definition do not change, simply make the model parameter in question fixed. 

I hope this helped. If you have any further questions concernig ELISa, feel free to ask. 

Sincerely,
Miro

**Comment by zihaowrez** [comment]
It works now. Thank you very much!
